#155 Update reference sequence numbering diagram
HGVSnomenclature/hgvs-nomenclature pull request #156
Opened 2024-03-10 19:32 UTC by reece

See #155

2024-03-18 20:59 UTC, reece commented
Here's the sole change:
https://hgvs-nomenclature--156.org.readthedocs.build/156/background/numbering/#figure

Compare with
https://hgvs-nomenclature.org/background/numbering/#figure

2024-03-19 01:50 UTC, ahwagner requested changes

2024-03-19 01:50 UTC, ahwagner commented on docs/stylesheets/extra.css
> -  background-color: #eee;
I happened to look at this figure this evening, while my browser was in dark mode. It looks like this:

![image](https://github.com/HGVSnomenclature/hgvs-nomenclature/assets/811065/8399fd91-17f8-4715-8193-4c4d732216bd)

I propose keeping the background styling for figures white–or at least doing so for this figure.

2024-03-19 03:40 UTC, reece commented
Good catch @ahwagner !

2024-03-19 13:25 UTC, ifokkema approved these changes
Looks good to me!

2024-03-19 19:55 UTC, ahwagner approved these changes

2024-03-19 20:00 UTC, jfjlaros approved these changes
This looks fine to me.

2024-03-19 20:00 UTC, merged