Add description of new hgvs-nomenclature-announcement group
HGVSnomenclature/hgvs-nomenclature pull request #191
Opened 2024-11-03 03:15 UTC by reece

A reviewer suggested that we have a second group for announcements only.

I think this is a good idea (and we'd discussed it previously). I created the group but didn't announce it anywhere. This PR adds that group to the top-level page.

If reviewers are in agreement, please merge this PR. 

If there is concern with adding another group, don't merge this PR and we'll discuss.

2024-11-03 03:23 UTC, ahwagner approved these changes
I agree, but would want at least one other person to approve before merge.

2024-11-05 17:39 UTC, ifokkema commented
Merging may depend on #194, as in, we may make the fixes discussed there, in this PR.

Regarding the changes currently in this PR, I'm not against merging, but I do find the loss of the "Contact us" a bit strange if we keep the part where we discuss how fast we'll be replying. That kind of implies that the person is contacting us, and not engaging with the community.

Unrelated to the content, I see the changes in this PR are sometimes not actual changes but a rewrapping of the existing content. Is that caused by settings within an IDE? Perhaps we should all take the same settings (or disable rewrapping of untouched content) to prevent diffs that are larger than needed. It makes me stare at the screen, trying to figure out what changed in that paragraph, only realizing after a while that the only thing changed was whitespace :sweat_smile:

2024-11-05 23:03 UTC, reece commented
I agree that whitespace changes are annoying when mixed with substantive changes. I usually avoid making such changes, but I think they're inevitable when moving paragraphs around (as happened here). If there are unnecessary whitespace changes, I apologize.

How would you feel if we merged this into main, then tackled #194 as a holistic rethinking of the entire section?

2024-11-07 01:24 UTC, ahwagner requested changes
New revisions have been added to this PR since my last review that undo HVNC-vetted text from #188. I recommend reverting those changes before merge.

2024-11-07 01:24 UTC, ahwagner commented on docs/index.md
> +We aim to respond within two business days of email receipt. If you haven't
We should not be overwriting this text added in #188 without committee discussion.

2024-11-07 01:40 UTC, reece commented
I reverted to main, then added just the blurb about the announcement group. We can pick up rewording this section in #194 (PR: #200). Please re-review.

2024-11-07 01:58 UTC, ahwagner approved these changes
LGTM (again)!

2024-11-07 04:18 UTC, merged

2024-11-07 12:23 UTC, ifokkema reviewed
LGTM!
(edit: I saw too late that it was merged already; ignore my useless comment, please :grin: )